### ISSUE TITLE
what if i want change the indexing model 

### ISSUE THREAD

**Issue by Lbaiall** [OSU-NLP-Group/HippoRAG#24]
what if i want change my indexing model by HF（with same config file format） and i see the source of code from src/.... file with colbertv2 names file,and dose anything else i need to change in my code ，like colbertv2_indexing.py，colbertv2_knn.py，create_graph.py ，and what support i should change in the code （i git url  (https://huggingface.co/castorini/mdpr-tied-pft-msmarco-ft-miracl-zh/tree/main) ）and it have some the other support language if you want see .......

**Comment by yhshu** [comment]
I think you can find relevant information in README.md about using HF models to index: https://github.com/OSU-NLP-Group/HippoRAG?tab=readme-ov-file#indexing-with-huggingface-retrieval-encoder-for-synonymy-edges-ie-contriever
