### ISSUE TITLE
colbertv2 load_node_vectors fail！

### ISSUE THREAD

**Issue by zhangyanbo2007** [OSU-NLP-Group/HippoRAG#25]
hipporag.py 
def load_node_vectors()
self.embed_model is None
failed, why?

**Comment by yhshu** [comment]
Hi, we can hardly help you unless you provide how you called this program, what the commands were, and what error messages were reported, thanks!

**Comment by yhshu** [comment]
Hi, this is an issue due to a recent update is causing the issue, I've submitted a PR and the latest version will run colbertv2 correctly.
