### ISSUE TITLE
fail to call the method "encode_text"

### ISSUE THREAD

**Issue by Jijun-Shi** [OSU-NLP-Group/HippoRAG#31]
the retrieve in bash config is colbert by default. when call the fucntion "init_embedding_model" ,it will return None, So, it fail to call the method "encode_text"

**Comment by yhshu** [comment]
Hello, which script are you running? If it's the ircot one (Retrieval - ColBERTv2), please pull the latest code and try again.

**Comment by Jijun-Shi** [comment]
> Hello, which script are you running? If it's the ircot one (Retrieval - ColBERTv2), please pull the latest code and try again.

hi, I can run the following script（for Indexing） successfully ！
###bash src/setup_hipporag_colbert.sh $DATA $LLM $GPUS $SYNONYM_THRESH $LLM_API###

but fail to run the script "python3 src/ircot_hipporag.py"（for retrieving）and I find  when I call function “init_embedding_model” in /HippoRAG-main/src/lm_wrapper/util.py, the funciton will return None. Then, the code execute the function "load_node_vectors" in hipporag.py, it will report a error. So, Can I build a new Class for loading some other model to repalce the GritWrapper or HuggingFaceWrapper?

**Comment by yhshu** [comment]
This is a known issue and I think the newest commit has fixed this:
https://github.com/OSU-NLP-Group/HippoRAG/blob/026514a77d4a761d91e4b1c9525329e670bd1cb1/src/hipporag.py#L475

Could you check if you're using this version and still have this problem?

**Comment by Jijun-Shi** [comment]
ok, but it meet the following mistake when i run the retrieve.sh
"No such file or directory: 'output/ircot/ircot_results_sample_hipporag_colbertv2_demo_1_gpt-4-1106-preview_no_ensemble_step_1_top_10_sim_thresh_0.8_damping_0.5.json", and i check the the file is not exist
what can I do next?

**Comment by Jijun-Shi** [comment]
> ok, but it meet the following mistake when i run the retrieve.sh "No such file or directory: 'output/ircot/ircot_results_sample_hipporag_colbertv2_demo_1_gpt-4-1106-preview_no_ensemble_step_1_top_10_sim_thresh_0.8_damping_0.5.json", and i check the the file is not exist what can I do nex

**Comment by yhshu** [comment]
Thanks for your response. I have submitted a PR and it should fix this problem after merging:
https://github.com/OSU-NLP-Group/HippoRAG/pull/32
