### ISSUE TITLE
How can we use it without openai? 

### ISSUE THREAD

**Issue by hemangjoshi37a** [OSU-NLP-Group/HippoRAG#39]
Is it possible to use it locally without openai api?

**Comment by Reza-Ardestani** [comment]
Yes, It is totally possible and It's simple.

Please visit my tutorial on this important matter as to how run RAGs locally:
[https://youtu.be/7wSUWx1eIF0?si=L7uMGXVbpv8iklg4](https://youtu.be/7wSUWx1eIF0?si=L7uMGXVbpv8iklg4
)

If you found this helpful, please consider sharing with friends.

Thank you,

**Comment by bernaljg** [comment]
Thanks @Reza-Ardestani for your tutorial but I do not think it's quite relevant to the question directly.

@hemangjoshi37a: Running HippoRAG locally using our repository is not currently tested but will be added in the future.

**Comment by hemangjoshi37a** [comment]
@bernaljg  @Reza-Ardestani  thanks
