### ISSUE TITLE
Table 3

### ISSUE THREAD

**Issue by Reza-Ardestani** [OSU-NLP-Group/HippoRAG#40]
Hello,

+ What does underlines in table 3 mean?
+ You have mentioned "results in significant improvements on all three datasets". How did you calculate significance? I would like to know the details of the approach. 

Thank you,

____
![image](https://github.com/user-attachments/assets/27f8308b-9482-4ed4-86e1-a736018b30b1)

**Comment by bernaljg** [comment]
- Underlined values usually highlight the second highest score in each column.
- We did not do any specific significance testing, we will change the wording in future versions.
