### ISSUE TITLE
A question regarding PPR on KB nodes

### ISSUE THREAD

**Issue by weicheng113** [OSU-NLP-Group/HippoRAG#48]
Dear authors,

Thanks for sharing this great paper and its implementation details. I have a question regarding the following implementation of PPR on KB nodes.

https://github.com/OSU-NLP-Group/HippoRAG/blob/5ddedf0f516c7bbed777ba54da680c8bb8fb8f84/src/hipporag.py#L524-L534

From my understanding, `self.kb_node_phrase_to_id` is document entity phrases to id mapping, and `reset_prob` is linked query entity phrase weighting. My question is when doing `personalized pagerank`, why graph node connections(one entity phrase connects to another entity phrase. It seems we have this information from triples?) are not considered? How are these nodes are connected at the moment? Do we treat all nodes are connected to each other?

Thanks in advance for your time.
Cheng

**Comment by yhshu** [comment]
Hello,

You're right about reset_prob and the phrase_to_id map. The personalized PageRank algorithm is a graph search algorithm, so node connections are considered. The graph `self.g` has stored nodes and edges. If you're asking why we don't assign edges with weights, it's because, so far, we've found that this doesn't help the graph search well.

Nodes are connected in two forms: 1. extraction of OpenIE and 2. synonymous edges. Please check our [paper](https://arxiv.org/abs/2405.14831) for more details. Thus, it's not that all nodes are connected to each other.

**Comment by weicheng113** [comment]
@yhshu Thanks for your time and prompt reply. Sorry for my negligence. I did not realize that connections are initialized at constructor method, which makes sense. Appreciate your help. Thanks.

**Comment by weicheng113** [comment]
@yhshu Hello, one more question regarding the following implementation.

https://github.com/OSU-NLP-Group/HippoRAG/blob/5ddedf0f516c7bbed777ba54da680c8bb8fb8f84/src/create_graph.py#L287-L295

Is there a need to consider if sim_edge has already existed from the original graph when it was built from triples? Otherwise, the node connection weight will be overwritten. We do the following instead for example. Just come across this. Not sure if there is such case and how often this will occur.

```python
graph_plus[sim_edge] += similarity_max * score
```

Thanks for your time and help.
Cheng Wei

**Comment by weicheng113** [comment]
Ah, re-read your comment above and check the implementation. The edge weights are not used for graph at the moment. So the above assigning weight or overwritten is not that important for now I guess. Thanks.

**Comment by yhshu** [comment]
I think @bernaljg can answer this better.

**Comment by weicheng113** [comment]
Thanks a lot @yhshu and @bernaljg, for your help and detailed explanation. It is clear now.

**Comment by yhshu** [comment]
When we conducted the research, models such as the BGE released earlier this year were contemporaneous work. Of course, users can choose their embedding models and we are also exploring this aspect.

**Comment by weicheng113** [comment]
Thanks @yhshu for your prompt reply. HippoRag is very attractive for real world application for its speed and elegant idea. Currently, I am more interested in its combination with Contriever(or other alternative dense embedding models). For ColBERTv2, there are a couple of issues in my mind. It is tightly coupled with faiss, which looks not very user-friendly. Secondly, incrementally adding or updating document in a document set seems complicated for ColBERTv2, needing to recalculate centroid and so on.

**Comment by weicheng113** [comment]
@yhshu Hello, just let you know I wrote an email to your paper contact about code improvement. Thanks.
