### ISSUE TITLE
where can I found query_to_kb.tsv & kb_to_kb.tsv & rel_kb_to_kb.tsv

### ISSUE THREAD

**Issue by hui-max** [OSU-NLP-Group/HippoRAG#49]
when I run the file setup_hipporag.sh , I found code like this and don't know how to find those file, and what those files used for, could you please explain it?
![image](https://github.com/user-attachments/assets/99e070bc-0716-4f4c-a000-b75fad24aa9c)

**Comment by yhshu** [comment]
Hello, these files should be generated during the previous steps. Could you show the full history of running the indexing part?

**Comment by hui-max** [comment]
Thank you for your help, I have known how to fix the problem
