### ISSUE TITLE
Can OpenIE be theoretically replaced with LLMs?

### ISSUE THREAD

**Issue by RemixaWorld** [OSU-NLP-Group/HippoRAG#54]
Thanks for your contributions!
Does the OpenIE just extract triples, not entity linking? Is it theoretically possible to replace this tool with LLMs?
If my understanding is wrong, please point it out for me, sincere thanks!

**Comment by yhshu** [comment]
Hello,
Prior to OpenIE, indexing does have a step to extract named entities that are used to further prompt the model to extract triples. 
Both NER and OpenIE are conducted via LLM.

**Comment by Remixa-python** [comment]
@yhshu 
Thanks for your patience!
I get it and I will explore further carefully!
