### ISSUE TITLE
setting chunk size of chunk_corpus function

### ISSUE THREAD

**Issue by doncat99** [OSU-NLP-Group/HippoRAG#56]
def chunk_corpus(corpus: list, chunk_size: int = 64) -> list:
    """
    Chunk the corpus into smaller parts. Run the following command to download the required nltk data:
    python -c "import nltk; nltk.download('punkt')"

    @param corpus: the formatted corpus, see README.md
    @param chunk_size: the size of each chunk, i.e., the number of words in each chunk
    @return: chunked corpus, a list
    """
the default chunk_size is 64, is that the best practice? I tried with 150, and the entity count is the same as 64, but 10% more relationships were obtained.

**Comment by yhshu** [comment]
The best practice depends on your scenarios. I'd suggest use the default value first and see the performance. Then, gradually tune this number.

**Comment by doncat99** [comment]
> The best practice depends on your scenarios. I'd suggest use the default value first and see the performance. Then, gradually tune this number.

Thanks for the advice. Recent two months many RAG Forms suddenly sprung up, and so as to the optimization approach for RAG as well. Will you share some ideas from your point of view?

**Comment by yhshu** [comment]
Hello. Given your past experience, I'd say don't set it too long, e.g., each chunk for 128 or less.
