### ISSUE TITLE
combined with ircot

### ISSUE THREAD

**Issue by victttt** [OSU-NLP-Group/HippoRAG#58]
when i change the --max_step to combine with IRCoT, it showed me the error passage, i don't know why, can you help me? thank you!
<img width="585" alt="截屏2024-10-15 09 38 17" src="https://github.com/user-attachments/assets/f741251c-ffb7-411f-8ef1-80a84ab58e3f">

**Comment by yhshu** [comment]
You should check why `new_thought` is None. This is probably because LLM doesn't generate that.
