### ISSUE TITLE
musique data format issue

### ISSUE THREAD

**Issue by fantastic-413** [OSU-NLP-Group/HippoRAG#59]
In the `musique.json` file, the data format of `paragraphs` is as follows:
![image](https://github.com/user-attachments/assets/f3a6e42f-e5bd-4492-960d-533af0aaf31b)
In the code processing, the non-existent `text` attribute is used, resulting in an error:
![image](https://github.com/user-attachments/assets/19bd5967-85eb-43e8-8eba-0b11ce1daf66)
![image](https://github.com/user-attachments/assets/651580c9-d8bd-4401-93cb-6573cda65123)
Should it be replaced with `item['paragraph_text']`?

**Comment by yhshu** [comment]
Sure you can modify that to make it work.

**Comment by fantastic-413** [comment]
Thanks for your reply.
